### ISSUE TITLE
How to download train data and pretrained models

### ISSUE THREAD

**Issue by emepetres** [ChengChen-ai/Sky-Segmentation#2]
Hi @ChengChen-ai , I came across your repo and interested me your results.

I've tried to download the train images and pre-trained models, but it seems not an easy task for non-chinese users. In baidu website it seems I'm only able to download netdisk binary, and it seems I need an account or something to download from my computer but it's being a complex task as I don't know anything about chinese.

Would it be possible for you to provide a more direct link like using google drive or wetransfer?

Thanks!

-------------
Update:
I managed to download some files one by one using `oneleaf.icu`, but this is far than ideal.

**Comment by ssskhan** [comment]
You can download them from this link:
https://drive.google.com/drive/folders/1RPXrciyyddctFbJAjhzjN50NrBiFl8wi
